# Generated by Django 3.2.23 on 2024-01-01 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_category_product_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='test',
            new_name='category',
        ),
    ]
